--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -40,4 +40,4 @@
           pip install -r backend/requirements-dev.txt
 
       - name: Run unit tests
-        run: pytest backend
+        run: pytest backend